### ISSUE TITLE
Default values file includes data which should not be default

### ISSUE THREAD

**Issue by dannysauer** [diggerhq/helm-charts#11]
Default values for ingress include a new ingress class name of "test" which breaks existing ingress implementations which previously specified the ingress annotation `kubernetes.io/ingress.class: nginx` (except in the extremely unlikely situation where someone is using an ingress class of "test").  Aside from the breakage, it includes several additional default values which would be inappropriate in an active deployment.  Those should probably be a commented-out example. :)

https://github.com/diggerhq/helm-charts/blob/main/charts/digger-backend/values.yaml#L45-L55

**Comment by motatoes** [comment]
resolved in #14
