### ISSUE TITLE
helm application version isn't being updated in sync with container

### ISSUE THREAD

**Issue by dannysauer** [diggerhq/helm-charts#13]
When a new digger backend container is published, the helm chart isn't being updated.

There are a couple of ways to make this happen.  Personally, I really like using Renovate for updating dependencies.  It'd probably be useful for the main repo, and could be reused to automatically open PRs against this repo when the container updates.  The manager at https://docs.renovatebot.com/modules/manager/helm-values/ could handle this.

There are also actions which can be installed on the main repo to open a PR against this repo using an automation account.  I can share general thoughts on how I do it in a few places, but ultimately there are several opinions on how to do it. :)

**Comment by motatoes** [comment]
I actually realised that the value of `appVersion`  isn't used, we instead are using digger.image.tag to specify version. I'm thinking that we should just hardcode it to "latest" and have it overriden by the user as a chart value. I don't think it makes sense to release a new chart everytime we have a new release (we release often)

**Comment by motatoes** [comment]
Was thinking of this change @dannysauer let me know your thoughts https://github.com/diggerhq/helm-charts/pull/14

I realise the version is a recommended label but I think in this case would rather the user sets the label themselves

**Comment by dannysauer** [comment]
More comments in the PR! :)

**Comment by motatoes** [comment]
resolved in #14
